function Untitled = importfile_ISIIS(filename, dataLines)
%IMPORTFILE Import data from a text file
%  UNTITLED = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  UNTITLED = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  Untitled = importfile("C:\work\LTER\EN644\ISIIS\SledData\20190821_221205.260_BELLAMARE_CSV_DATA_BELLAMARE_CSV_DATA.csv", [6, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 24-Aug-2019 08:29:45

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [6, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 27);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["UNIX_timestamp", "LCM_event_timestamp", "AANDERAA_AIR_SATURATION", "AANDERAA_O2_UM", "AANDERAA_TEMP_C", "ALTITUDE_M", "ALTITUDE_OK", "CTD_CONDUCTIVITY", "CTD_PRESSURE", "CTD_SALINITY", "CTD_SOUND_VELOCITY", "CTD_TEMPERATURE_DEG_C", "DEPTH_M", "FLUOROMETER_BACKSCATTER_RAW", "FLUOROMETER_CHLOROPHYLL_RAW", "FORWARD_VELOCITY_M_PER_S", "HEADING_DEG", "PITCH_DEG", "ROLL_DEG", "SEABIRD_PAR_ADC", "SEABIRD_PAR_VDC", "TS_GPS_EPOCH_TIME", "TS_LATITUDE_DEG", "TS_LONGITUDE_DEG", "VERTICAL_VELOCITY_M_PER_S", "count_publish", "sender_id"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "categorical"];
opts = setvaropts(opts, 27, "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
Untitled = readtable(filename, opts);

end